development:
  adapter: postgresql
  encoding: utf8
  username: root
  password:
  database: suenophoto_development

test:
  adapter: postgresql
  encoding: utf8
  username: root
  password:
  database: suenophoto_test

production:
  adapter: postgresql
  encoding: utf8
  database: suenophoto_production

staging:
  adapter: postgresql
  encoding: utf8
  database: suenophoto_staging
